Refactor jupyter to modules
EPFL-ENAC/LUTS-pneuma-simulator pull request #1
Opened 2024-11-08 14:53 UTC by hsolleder

# Prework

- [X] I understand and agree to this repository's [code of conduct](https://github.com/ltelab/disdrodb/blob/main/CODE_OF_CONDUCT.md).
- [X] I understand and agree to this repository's [contributing guidelines](https://github.com/ltelab/disdrodb/blob/main/CONTRIBUTING.md).
- [ ] I have already submitted an [issue](https://github.com/ltelab/disdrodb/issues) or [discussion thread](https://github.com/ltelab/disdrodb/discussions) to discuss my idea with the maintainers.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [X] Refactor
- [X] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [X] It's submitted to the branch named as follow :
  - Add a reader: `reader-<institute>-<campaign>`
  - Fix a bug: `bugfix-<some_key>-<word>`
  - Improve the doc: `doc-<some_key>-<word>`
  - Add a new feature: `feature-<some_key>-<word>`
  - Refactor some code: `refactor-<some_key>-<word>`
  - Optimize some code: `optimize-<some_key>-<word>`
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] Don't forget to link PR to issue if you are solving one.
- [ ] All tests are passing.
- [ ] New/updated tests are included

# Summary

This pull request includes significant changes to the `pNeuma-simulator` project, focusing on adding documentation and implementing core functionalities. The most important changes are grouped into documentation setup and core functionalities.

Of note, the deployment of the documentation to GitHub pages or ReadTheDocs is currently not possible, given that the repository is private.

**Documentation Setup:**

* Created a `Makefile` in the `docs` directory to facilitate building Sphinx documentation.
* Added Sphinx configuration in `docs/conf.py` for building and customizing the documentation.
* Initialized the documentation structure with `index.rst` and `api.rst` files in the `docs` directory. [[1]](diffhunk://#diff-8d068e8797e88947c320f79e856c3e16a72b730124a8f9d7031e2c4680dfa534R1-R21) [[2]](diffhunk://#diff-0ee295c29def16f570f86378eff8ba37315e464d415e731d5d8ea2e67ce16f68R1-R4)
* Added docstrings to all functions

**Core Functionalities:**

* Refactored the code, moving from an all-in-one Jupyter notebook to a modular package structure
* Managed the dependencies using Poetry
* Made the package installable via `pip`

**Project Setup:**

* Updated the `README.md` to include installation instructions, usage details, and documentation building steps.

2024-11-26 10:09 UTC, pierreleripoll requested changes
Looks very cool ! Docs generation is great, and the submodules seems very well documented. 
Though it's difficult to get through a deep code review, because documentation lack a little bit of "general purpose" explanation. Like type of data, maybe a little example data & use case, and also what does every submodule does, how it can be helpfull (for me or for a random researcher). Right now I can't really review the specific modules because I don't quite understand what they are supposed to do.

Anyway super cool direction of the whole project !

2024-11-26 10:09 UTC, pierreleripoll commented on README.md
ia proposed some improvements how do you fell about it ?

#### **1. General Enhancements**
- **Add a Project Description**: Include a brief overview of the project's purpose, target audience, and key functionalities. For example:
  > *The pNeuma-simulator is a Python-based tool for simulating multispecies urban traffic flow dynamics. It aims to provide an open-source, reproducible, and FAIR framework for traffic engineers and researchers in physics to analyze urban mobility scenarios.*
  
- **Highlight Key Features**: Mention features such as modular code structure, Jupyter notebook integration, and focus on reproducibility.

---

#### **2. Installation Section**
- **Clarify System Requirements**:
  - Specify supported operating systems (e.g., Linux, macOS, Windows) and Python versions.
  - Example:
    > *This package supports Python 3.8 and above. It has been tested on Linux and macOS.*

- **Handle macOS-specific Installation**: Instead of a separate macOS instruction, explain the need for quotes and suggest it for macOS users.
  ```bash
  $ pip install -e .[dev]
  ```
  *For macOS users, replace `.[dev]` with `'.[dev]'`.*

- **List Dependencies**: Provide a brief note about dependencies (managed via Poetry or otherwise) and whether they are installed automatically.

---

#### **3. Usage Section**
- **Add a Usage Example**:
  - Provide a simple example of running a simulation, referencing a typical workflow in the notebook. For instance:
    ```python
    from pneuma_simulator import initialize_simulation

    simulation = initialize_simulation(config)
    simulation.run()
    ```

- **Clarify Notebook Location**:
  - The link `pNeuma_simulator/notebooks/pNEUMA-simulator.ipynb` does not match the usual GitHub file path format. Consider specifying the full path relative to the repository root or the expected location post-clone.

---

#### **4. Documentation Section**
- **Expand on Documentation Setup**:
  - Include any prerequisites for building the documentation (e.g., `pip install sphinx` or `poetry install`).
  - Highlight the output location of the built documentation (e.g., `docs/_build/html`).

- **Example**:
  > To build the documentation, ensure Sphinx is installed. Then, navigate to the `docs` directory and run:
  > ```bash
  > $ make html
  > ```
  > The generated HTML files can be found in the `docs/_build/html` directory.

- **Future Plans**:
  - If there are plans for publishing the documentation on GitHub Pages or ReadTheDocs, include a placeholder note (e.g., *Documentation hosting is planned once the repository becomes public.*).

---

#### **5. Badges and Status**
- **Add More Badges**:
  - Include badges for Python version compatibility, license, and code coverage if applicable. Example:
    ```markdown
    ![Python Version](https://img.shields.io/badge/python-3.8%2B-blue)
    ![License](https://img.shields.io/badge/license-MIT-green)
    ```

2024-11-26 10:09 UTC, pierreleripoll commented on README.md
I feel like a little introduction to the projeoct (it's a traffic simulator) is nice to have
I'm not so sure macOs is important, but maybe the usage example is also cool ?
Nothing absolutely necessary though, more like "nice to have"

2024-11-26 10:09 UTC, pierreleripoll commented on docs/Makefile
you could have a Makefile in the root folder that calls make command of the docs/ one. This way no need to "cd docs/ & make docs"

2024-11-26 10:09 UTC, pierreleripoll commented on docs/api.rst
I'm not sure if that's the right place to mention this but it's missing a "whole purpose" documentation. 
It's important that front page of docs contains the main purpose of this package + use case eg :  an example data, and use case with every submodule of this package

2024-11-26 10:09 UTC, pierreleripoll commented on docs/api.rst
For me as code reviewer it's difficult to understand what kind of data I could use this package with, and quickly understand what I can do with it. Can we add it ? It would also help the code review, because right now I canno't test the submodules since I don't know what kind of data I should use it with and what kind of result I should have with

2024-11-26 10:09 UTC, pierreleripoll commented on pNeuma_simulator/params.py
Can we have more documentation about this file ? Like why thoses variabels are hard coded ?

2024-11-28 08:21 UTC, hsolleder commented on docs/Makefile
Done in #85208a9

2024-11-28 08:27 UTC, hsolleder commented on pNeuma_simulator/params.py
The variables were hard-coded within functions, I placed them in `params.py` as a temporary workaround before passing a parameters structure to the functions needing them. Adding this structure is beyond the scope of the pilot, so it should stay like this

2024-12-09 07:53 UTC, pierreleripoll approved these changes

2024-12-20 07:51 UTC, merged